management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: ["*"]
      path-mapping:
        prometheus: metrics
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
      logback: false
      process:
        files: false
        uptime: true
        cpu: true
      system:
        cpu: false
  server:
    port: 9090
server:
  error:
    whitelabel:
      enabled: false
  port: 8888
spring:
  profiles:
    active: production
  application:
    name: "Demo Service"