management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: ["*"]
      path-mapping:
        prometheus: metrics
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
      logback: false
      process:
        files: false
        uptime: true
        cpu: true
      system:
        cpu: false
  server:
    port: 9090
server:
  error:
    whitelabel:
      enabled: false
  port: 8888
spring:
  profiles:
    active: production
  application:
    name: "Demo Service"
  datasource:
    url: jdbc:postgresql://localhost:5555/rental
    username: rental
    password: rental
  jpa:
    properties:
#      uncomment for JPA script creation
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/resources/db/migration/V001__create_tables.sql
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  #   comment if you use flyway - It's not a good idea to rely on automatic creation of migrations
#    hibernate:
#      ddl-auto: update
  flyway:
    enabled: true